### ISSUE TITLE
Immediately start service

### ISSUE THREAD

**Issue by szechyjs** [opscode-cookbooks/enterprise-chef-common#19] opened 2014-11-10 15:48 UTC
Need a way to enable and immediately start a component_runit_service.

**Comment by smith** [comment] 2015-05-15 04:12
@szechyjs I don't see anything in the definition telling it to wait for the end of the Chef client run to start the service. It could be that the run script has completed but the service isn't ready yet.

Have you found another way around this. I'm going to close it since there hasn't been any activity and I'm not able to reproduce. Please reopen if you would like some help looking at it more deeply. Thanks!

**Closed by smith** 2015-05-15 04:12 UTC
